server.port=8080
spring.datasource.url=jdbc:h2:mem:medibookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# H2 Console Configuration & Embedded Frame Support
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# Allow pages to be embedded inside iframes on the same origin (localhost:8080)
server.servlet.session.cookie.same-site=lax